### ISSUE TITLE
Can't get DOM width or height

### ISSUE THREAD

**Issue by ywiyogo** [CarterLi/vue3-echarts#1]
Hi @CarterLi ,thanks for creating this Echarts binding for Vue3!
In the point 3 where shall I place the line with `(this.$refs.chart as VueEcharts).refreshOption();`?

I pass my option to the option props. However, I got this error:
`Can't get DOM width or height. Please check dom.clientWidth and dom.clientHeight. They should not be 0.For example, you may need to call this in the callback of window.onload.`
How can I fix the error?
My template code of my component is like this:
```
<template>
  <div class="col-auto row">
    <template v-if="checkValues()">
      <vue-echarts :option="line" style="height: 500px" ref="chart" />
    </template>
  </div>
</template>

<script>
import { VueEcharts } from 'vue3-echarts';
export default {
data: () => ({
    loading: true,
    line: {....}
}),
};
</script>
```

**Comment by CarterLi** [comment]
> In the point 3 where shall I place the line with (this.$refs.chart as VueEcharts).refreshOption();?

You don't need to call `refreshOption` when `vue-echarts` is created. You need to call `refreshOption` when the option is updated.

> However, I got this error

It was strange.  Could you provide more info such as stack trace and more importantly the status of `vue-echarts` element when the exception was thrown?

**Comment by ywiyogo** [comment]
Thanks @CarterLi  for the hint checking the element. This is the status of my `vue-charts` element:
`<div class="vue-echarts" style="height: 500px; -webkit-tap-highlight-color: transparent; user-select: none; position: relative;" _echarts_instance_="ec_1636225806299"><div style="position: relative; width: 0px; height: 500px; padding: 0px; margin: 0px; border-width: 0px;"><canvas data-zr-dom-id="zr_0" width="0" height="500" style="position: absolute; left: 0px; top: 0px; width: 0px; height: 500px; user-select: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); padding: 0px; margin: 0px; border-width: 0px;"></canvas></div><div class=""></div></div>`

I created that with this vue template code just like in your README.md:
```
<template>
  <vue-echarts :option="line" style="height: 500px;" ref="chart" />
</template>
```
The error is gone after I add the width, e.g. `style="height: 500px; width: 1000px;"`.

**Comment by CarterLi** [comment]
The root element of vue-echarts is div, it should act as `width: 100%` by default.

**Comment by xzegga** [comment]
Any luck with this issue. Today at 2023 I am still having this issue but with React.
`[ECharts] Can't get DOM width or height. Please check dom.clientWidth and dom.clientHeight. They should not be 0.For example, you may need to call this in the callback of window.onload.`

**Comment by slavaGanzin** [comment]
@xzegga you could set width or height in `init(element, theme, {width: 1000, height: 1000})`

**Comment by yfragata-rcx** [comment]
try this on your container CSS:

#chart-container {
  position: relative;
  height: 100vh;
  overflow: hidden;
}

**Comment by pearcemc** [comment]
I also had this with React (inside some Joy UI component).

Following slava's suggestion, this call fixed it up for me:

```
    <ReactEcharts
      option={option}
      style={{ width: '300px', height: '300px', minHeight: '300px', minWidth: '300px'}}
    />
```

**Comment by condorheroblog** [comment]
> I also had this with React (inside some Joy UI component).
> 
> Following slava's suggestion, this call fixed it up for me:
> 
> ```
>     <ReactEcharts
>       option={option}
>       style={{ width: '300px', height: '300px', minHeight: '300px', minWidth: '300px'}}
>     />
> ```

This method didn't work for me.

According to https://github.com/ecomfe/vue-echarts/issues/525#issuecomment-2551475849, this works for me:

```tsx
<ReactECharts
	opts={{ height: "auto", width: "auto" }}
	option={option}
/>
```
