### ISSUE TITLE
TS 版本有问题 导致编译错误

### ISSUE THREAD

**Issue by CakeCheng** [CarterLi/vue3-echarts#3]
TS 版本有问题 导致编译错误

**Comment by MrCube42** [comment]
The issue occurs when running `vue-tsc` against the codebase that is using `vue3-echarts`. The error says how to fix it, too:
> Property '$el' will overwrite the base property in 'VueComponentBase'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.

I forked this repo and fixed it with the following commit. Could be integrated via a MR.

**Comment by CarterLi** [comment]
Thanks @MrCube42

**Comment by MrCube42** [comment]
@CarterLi You're welcome. Will there be a version 1.0.5 on npm soon? We are currently using my forked version and would rather use the one on npm.
