### ISSUE TITLE
i need refresh data from api like this How can i 

### ISSUE THREAD

**Issue by Ruttanachote** [CarterLi/vue3-echarts#5]
https://echarts.apache.org/en/api.html#echartsInstance

 function greetings() {

      mychart.setOption({
        option.color = ['#1319CCs'];
       option.xAxis = {
       data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
        type: 'category',
       };
      option.series = [
        {
          data: ['150', '230', '224', '218', '135', '147', '260'],
         name: 'Line1',
          type: 'line',
         },
         {
         data: ['130', '230', '424', '618', '125', '117', '620'],
        name: 'Line2',
         type: 'line',
         },
       ];
      });

    }
    
        setInterval(greetings, 2000);

**Comment by Ruttanachote** [comment]
echartsInstance.setOption.    >  ???

**Comment by Ruttanachote** [comment]
or update data only after render default  option

**Comment by Ruttanachote** [comment]
look like dinamic data

**Comment by CarterLi** [comment]
use refreshOption

https://github.com/CarterLi/vue3-echarts#how-to-use
